# Generated by Django 2.2.5 on 2022-05-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='overtime_categories',
            fields=[
                ('overtime_category_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('overtime_category_name', models.CharField(max_length=50)),
                ('overtime_category_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overtime_category_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('overtime_category_deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vacations',
            fields=[
                ('vacation_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('vacation_leaving_date', models.DateField()),
                ('vacation_coming_date', models.DateField()),
                ('vacation_is_paid', models.BooleanField()),
                ('vacation_is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('vacation_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vacation_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('vacation_deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('vacation_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='overtime',
            fields=[
                ('overtime_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('overtime_status', models.BooleanField()),
                ('overtime_hours', models.IntegerField()),
                ('overtime_date', models.DateField()),
                ('overtime_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('overtime_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('overtime_deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('overtime_overtime_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees_requests.overtime_categories')),
                ('overtime_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='loans',
            fields=[
                ('loan_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField()),
                ('loan_started_date', models.DateField()),
                ('loan_period', models.IntegerField()),
                ('loan_number_of_complete_payment', models.IntegerField(default=0, null=True)),
                ('loan_status', models.BooleanField(default=False, null=True)),
                ('loan_is_approved', models.BooleanField(default=False, null=True)),
                ('loan_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('loan_deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('loan_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='complains_and_suggestions',
            fields=[
                ('complains_and_suggestions_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('complains_or_suggestions', models.BooleanField()),
                ('complains_and_suggestions_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('complains_and_suggestions_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('complains_and_suggestions_deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('complains_and_suggestions_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
