# Generated by Django 2.2.5 on 2022-05-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='overtime_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
