# Generated by Django 2.2.5 on 2022-02-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees_requests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='vacation_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.users'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='overtime_overtime_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees_requests.overtime_types'),
        ),
        migrations.AddField(
            model_name='loans',
            name='loan_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.users'),
        ),
        migrations.AddField(
            model_name='complains_and_suggestions',
            name='complains_and_suggestions_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.users'),
        ),
    ]
