# Generated by Django 2.2.5 on 2022-05-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_requests', '0003_auto_20220321_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='loan_admin_approval',
        ),
        migrations.AddField(
            model_name='loans',
            name='loan_is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_number_of_complete_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_status',
            field=models.BooleanField(default=False),
        ),
    ]
