# Generated by Django 2.2.5 on 2022-05-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_requests', '0004_auto_20220503_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='loan_type',
        ),
    ]
