# Generated by Django 2.2.5 on 2022-05-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_requests', '0005_remove_loans_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan_is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_number_of_complete_payment',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
