# Generated by Django 2.2.5 on 2022-05-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_requests', '0006_auto_20220503_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='vacation_is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
