# Generated by Django 2.2.5 on 2022-03-07 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_DOB',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_activation_hash',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_address_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_attachment_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_created_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_deleted_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_education_degree',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_employee_department',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_job_title_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_mobile',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_nationality_ID',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_type_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_updated_at',
        ),
        migrations.AddField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='email', max_length=60, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='password', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='username', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
