# Generated by Django 2.2.5 on 2022-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
