# Generated by Django 2.2.5 on 2022-03-12 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220312_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_DOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
