# Generated by Django 2.2.5 on 2022-03-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220312_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_mobile',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
