# Generated by Django 2.2.5 on 2022-03-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220312_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_mobile',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
