# Generated by Django 2.2.5 on 2022-03-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_users_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id_number',
            field=models.CharField(default='8784888930', max_length=10),
        ),
    ]
