# Generated by Django 2.2.5 on 2022-05-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20220324_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_middle_name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
