# Generated by Django 2.2.5 on 2022-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220526_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_salary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
