# Generated by Django 2.2.5 on 2022-06-08 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_users_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
