# Generated by Django 2.2.5 on 2022-06-12 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20220608_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/upload/users_photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png,jpg,jpeg'])]),
        ),
    ]
