# Generated by Django 2.2.5 on 2022-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('event_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=30)),
                ('event_title', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=50)),
                ('event_created_at', models.DateTimeField()),
                ('event_updated_at', models.DateTimeField()),
                ('event_deleted_at', models.DateTimeField()),
            ],
        ),
    ]
