# Generated by Django 2.2.5 on 2022-03-21 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220222_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
