# Generated by Django 2.2.5 on 2022-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('account_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=50)),
                ('account_phone', models.IntegerField()),
                ('account_email', models.CharField(max_length=50, unique=True)),
                ('account_address', models.CharField(max_length=264)),
                ('account_created_at', models.DateTimeField()),
                ('account_updated_at', models.DateTimeField()),
                ('account_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='allowances',
            fields=[
                ('allowance_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('allowance_type', models.CharField(max_length=50)),
                ('allowance_amount', models.IntegerField()),
                ('allowance_created_at', models.DateTimeField()),
                ('allowance_updated_at', models.DateTimeField()),
                ('allowance_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='allowances_and_contracts',
            fields=[
                ('allowance_and_contract_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('allowance_and_contract_created_at', models.DateTimeField()),
                ('allowance_and_contract_updated_at', models.DateTimeField()),
                ('allowance_and_contract_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='annual_bounces',
            fields=[
                ('annual_bounce_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('annual_bounce_amount', models.IntegerField()),
                ('annual_bounce_created_at', models.DateTimeField()),
                ('annual_bounce_updated_at', models.DateTimeField()),
                ('annual_bounce_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='incentives',
            fields=[
                ('incentive_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('incentive_amount', models.IntegerField()),
                ('incentive_created_at', models.DateTimeField()),
                ('incentive_updated_at', models.DateTimeField()),
                ('incentive_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='payrolls',
            fields=[
                ('payroll_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('payroll_net_salary', models.IntegerField()),
                ('payroll_sign_off', models.BooleanField(default=False)),
                ('payroll_sign_off_date', models.DateField()),
                ('payroll_created_at', models.DateTimeField()),
                ('payroll_updated_at', models.DateTimeField()),
                ('payroll_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='punishments',
            fields=[
                ('punishment_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('punishment_amount', models.IntegerField()),
                ('punishments_cause', models.TextField()),
                ('punishment_created_at', models.DateTimeField()),
                ('punishment_updated_at', models.DateTimeField()),
                ('punishment_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('reward_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('reward_amount', models.IntegerField()),
                ('reward_cause', models.TextField()),
                ('reward_created_at', models.DateTimeField()),
                ('reward_updated_at', models.DateTimeField()),
                ('reward_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='social_insurances',
            fields=[
                ('social_insurance_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('social_insurance_amount', models.IntegerField()),
                ('social_insurance_created_at', models.DateTimeField()),
                ('social_insurance_updated_at', models.DateTimeField()),
                ('social_insurance_deleted_at', models.DateTimeField()),
            ],
        ),
    ]
