# Generated by Django 2.2.5 on 2022-03-23 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_auto_20220321_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='annual_bounces',
            new_name='annual_bonuses',
        ),
        migrations.RenameField(
            model_name='annual_bonuses',
            old_name='annual_bounce_amount',
            new_name='annual_bonus_amount',
        ),
        migrations.RenameField(
            model_name='annual_bonuses',
            old_name='annual_bounce_created_at',
            new_name='annual_bonus_created_at',
        ),
        migrations.RenameField(
            model_name='annual_bonuses',
            old_name='annual_bounce_deleted_at',
            new_name='annual_bonus_deleted_at',
        ),
        migrations.RenameField(
            model_name='annual_bonuses',
            old_name='annual_bounce_id',
            new_name='annual_bonus_id',
        ),
        migrations.RenameField(
            model_name='annual_bonuses',
            old_name='annual_bounce_updated_at',
            new_name='annual_bonus_updated_at',
        ),
        migrations.RenameField(
            model_name='annual_bonuses',
            old_name='annual_bounce_user_id',
            new_name='annual_bonus_user_id',
        ),
        migrations.CreateModel(
            name='bank_account',
            fields=[
                ('bank_account_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('bank_account_bank_name', models.CharField(max_length=50)),
                ('bank_account_card_holder_name', models.CharField(max_length=100)),
                ('bank_account_iban_number', models.CharField(max_length=30)),
                ('payroll_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payroll_updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('payroll_deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('bank_account_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
