# Generated by Django 2.2.5 on 2022-04-07 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0016_auto_20220324_0232'),
        ('finance', '0004_auto_20220324_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishments',
            name='punishment_job_title_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='job_management.job_titles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewards',
            name='reward_job_title_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='job_management.job_titles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='punishments',
            name='punishments_cause',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
