# Generated by Django 2.2.5 on 2022-04-07 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20220407_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishments',
            name='punishment_job_title_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='job_management.job_titles'),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='reward_job_title_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='job_management.job_titles'),
        ),
    ]
