# Generated by Django 2.2.5 on 2022-04-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20220407_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punishments',
            name='evaluation_date',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='evaluation_date',
        ),
        migrations.AddField(
            model_name='punishments',
            name='punishment_evaluation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rewards',
            name='reward_evaluation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
