# Generated by Django 2.2.5 on 2022-04-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20220407_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punishments',
            old_name='punishment_evaluation_date',
            new_name='punishment_date',
        ),
        migrations.RenameField(
            model_name='rewards',
            old_name='reward_evaluation_date',
            new_name='reward_date',
        ),
    ]
