# Generated by Django 2.2.5 on 2022-05-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20220407_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolls',
            name='payroll_contract_id',
        ),
        migrations.RemoveField(
            model_name='payrolls',
            name='payroll_sign_off',
        ),
        migrations.RemoveField(
            model_name='payrolls',
            name='payroll_sign_off_date',
        ),
    ]
