# Generated by Django 2.2.5 on 2022-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_payrolls_payroll_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolls',
            name='payroll_signed_off',
            field=models.BooleanField(default=False),
        ),
    ]
