# Generated by Django 2.2.5 on 2022-05-30 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_payrolls_payroll_signed_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolls',
            name='payroll_sign_off_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
