# Generated by Django 2.2.5 on 2022-03-21 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0014_auto_20220320_0137'),
        ('track_performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluations',
            name='evaluation_department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_management.departments'),
        ),
        migrations.AddField(
            model_name='evaluations',
            name='evaluation_job_title_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_management.job_titles'),
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='evaluation_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='evaluation_deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='evaluation_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='evaluation_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
