# Generated by Django 2.2.5 on 2022-03-21 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track_performance', '0005_evaluations_evaluation_overall_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='evaluation_date',
            field=models.DateField(),
        ),
    ]
