# Generated by Django 2.2.5 on 2022-03-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_performance', '0006_auto_20220321_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluations',
            name='evaluation_date',
            field=models.DateTimeField(),
        ),
    ]
