# Generated by Django 2.2.5 on 2022-03-27 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track_performance', '0008_auto_20220321_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_file',
            fields=[
                ('attendance_file_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('attendance_file_name', models.TextField(blank=True, default=None, null=True)),
                ('attendance_file_date', models.DateField()),
                ('attendance_file_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
