# Generated by Django 2.2.5 on 2022-03-27 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_performance', '0009_auto_20220327_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_file',
            name='attendance_file_name',
        ),
        migrations.AddField(
            model_name='attendance_file',
            name='attendance_file',
            field=models.FileField(default='asda', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='static/upload/attendance_files'),
            preserve_default=False,
        ),
    ]
