# Generated by Django 2.2.5 on 2022-03-27 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_performance', '0010_auto_20220327_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_file',
            name='attendance_file',
            field=models.FileField(upload_to='static/upload/attendance_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
    ]
