# Generated by Django 2.2.5 on 2022-03-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_performance', '0011_auto_20220327_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_half_day',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
