# Generated by Django 2.2.5 on 2022-03-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_performance', '0012_auto_20220328_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_total_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_duration',
            field=models.TimeField(default='12:12:12'),
            preserve_default=False,
        ),
    ]
