# Generated by Django 2.2.5 on 2022-03-28 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_performance', '0013_auto_20220328_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_source_file_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='track_performance.attendance_file'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_clock_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_clock_out',
            field=models.TimeField(),
        ),
    ]
