# Generated by Django 2.2.5 on 2022-02-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('department_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('department_created_at', models.DateTimeField()),
                ('department_updated_at', models.DateTimeField()),
                ('department_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='job_locations',
            fields=[
                ('job_locations_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('job_locations_name', models.CharField(max_length=50)),
                ('job_locations_description', models.TextField(blank=True, null=True)),
                ('job_locations_created_at', models.DateTimeField()),
                ('job_locations_updated_at', models.DateTimeField()),
                ('job_locations_deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='job_titles',
            fields=[
                ('job_title_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('job_title_code', models.IntegerField()),
                ('job_title_description', models.TextField(blank=True, null=True)),
                ('job_title_qualification', models.TextField(blank=True, null=True)),
                ('job_title_opening_position', models.CharField(max_length=264)),
                ('job_title_hour_price', models.IntegerField()),
                ('job_title_overtime_percentage', models.IntegerField()),
                ('job_title_available_online', models.BooleanField()),
                ('job_title_days_off', models.IntegerField()),
                ('job_title_status', models.BooleanField()),
                ('job_title_created_at', models.DateTimeField()),
                ('job_title_updated_at', models.DateTimeField()),
                ('job_title_deleted_at', models.DateTimeField()),
                ('job_title_department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='job_management.departments')),
                ('job_title_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='job_management.departments')),
            ],
        ),
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('contract_id', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('contract_status', models.BooleanField()),
                ('contract_hour_price', models.IntegerField()),
                ('contract_has_trail_period', models.BooleanField()),
                ('contract_expiry_date', models.DateField()),
                ('contract_approval', models.BooleanField()),
                ('contract_conditions', models.TextField(blank=True, null=True)),
                ('contract_created_at', models.DateTimeField()),
                ('contract_updated_at', models.DateTimeField()),
                ('contract_deleted_at', models.DateTimeField()),
                ('contract_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.accounts')),
            ],
        ),
    ]
