# Generated by Django 2.2.5 on 2022-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_titles',
            name='job_title_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
