# Generated by Django 2.2.5 on 2022-03-13 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0004_auto_20220313_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
