# Generated by Django 2.2.5 on 2022-03-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0005_auto_20220313_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_job_titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=150)),
                ('jtname', models.CharField(max_length=80)),
                ('hourPrice', models.CharField(max_length=5)),
            ],
        ),
    ]
