# Generated by Django 2.2.5 on 2022-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0006_add_job_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_titles',
            name='job_title_available_online',
        ),
        migrations.RemoveField(
            model_name='job_titles',
            name='job_title_code',
        ),
        migrations.RemoveField(
            model_name='job_titles',
            name='job_title_days_off',
        ),
        migrations.RemoveField(
            model_name='job_titles',
            name='job_title_description',
        ),
        migrations.RemoveField(
            model_name='job_titles',
            name='job_title_location',
        ),
        migrations.RemoveField(
            model_name='job_titles',
            name='job_title_opening_position',
        ),
        migrations.RemoveField(
            model_name='job_titles',
            name='job_title_overtime_percentage',
        ),
        migrations.RemoveField(
            model_name='job_titles',
            name='job_title_qualification',
        ),
        migrations.AddField(
            model_name='job_titles',
            name='job_title_name',
            field=models.CharField(default='default job title name', max_length=150),
            preserve_default=False,
        ),
    ]
