# Generated by Django 2.2.5 on 2022-03-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0007_auto_20220315_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_titles',
            name='job_title_deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job_titles',
            name='job_title_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
