# Generated by Django 2.2.5 on 2022-03-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0009_auto_20220315_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_job_titles',
        ),
    ]
