# Generated by Django 2.2.5 on 2022-03-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0011_departments_department_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='department_updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
