# Generated by Django 2.2.5 on 2022-03-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0012_auto_20220320_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='department_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
