# Generated by Django 2.2.5 on 2022-03-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0013_auto_20220320_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_titles',
            name='job_title_deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job_titles',
            name='job_title_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
