# Generated by Django 2.2.5 on 2022-03-23 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_management', '0015_auto_20220321_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='contract_account_id',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='contract_approval',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='contract_has_trail_period',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='contract_status',
        ),
        migrations.AddField(
            model_name='contracts',
            name='contract_auto_renewal',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracts',
            name='contract_starting_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracts',
            name='contract_user_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_conditions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
